Add missing entries on aloowlist
vrchat-community/creator-docs pull request #53
Opened 2023-08-25 21:39 UTC by slord399

All according to API
https://api.vrchat.cloud/api/1/config

2023-10-16 17:23 UTC, slord399 reviewed
Add more missing entry as per as 16th October 2023.

2023-10-17 04:37 UTC, Miner28 commented
Some of those were intentionally left out from what i remember.

2023-10-17 04:45 UTC, slord399 commented
I agree but people seems want to see it as full list as per as related canny.

2023-10-27 18:17 UTC, Faxmashine requested changes
Hi @slord399 ! Thanks again for the PR. Would you mind accepting the following changes?

The purpose of this list is to let world creators know what streaming services can be used without enabling 'trusted URLs'. Sites like Poly and Mixcloud should be in that list. Thank you for adding them!

The other sites you listed aren't streaming services, and world creators shouldn't rely on being able to access them.

2023-10-27 18:17 UTC, Faxmashine commented on Docs/docs/worlds/udon/image-loading.md
> +- CatsUDON (`*.catsudon.net`)
```suggestion
- Poly (`*.poly.jp`)
```

2023-10-27 18:17 UTC, Faxmashine commented on Docs/docs/worlds/udon/string-loading.md
> +* CatsUDON  (`*.catsudon.net`)
```suggestion
* Poly  (`*.poly.jp`)
```

2023-10-27 18:17 UTC, Faxmashine commented on Docs/docs/worlds/udon/video-players/www-whitelist.md
> +| Virtual Okinawa | `virtualokinawa-on-demand.contents.work` |
```suggestion
| Mixcloud | `mixcloud.com` |
| Poly | `*.poly.jp` |
```

2023-10-27 18:25 UTC, Miner28 commented
@Faxmashine Or another option I think would be to separate this list into 2 lists.
1. List of streaming services as it is right now that are trusted
2. List of all services that are whitelisted for privacy-concerned users to see the full list.

If that gets added, it could be hidden under a drop-down section.
However I don't know if that's really required/point of this page.

2023-10-27 18:30 UTC, slord399 commented
Yeah, I don't mind remove non-generic use service, but it can be changed in feature anyway.
+
Privacy concern and missing some site be not good on local regularation matter.
So I would bit to make other page which state all the untrusted URLs available to cope with local regularations which state you requred to have consent before actually using it. 
(As entry missing from docs means user may not consent to use these service anyway. Let's make it GDPR friendly at least.)

2023-10-29 23:54 UTC, slord399 reviewed
at leasat revised.
(anyway, still request to have separate docs for list all domains which used when untrusted URLs is opt-out.)

2023-10-30 15:40 UTC, Faxmashine approved these changes
Thank you for the changes!

2023-10-30 15:41 UTC, merged