warn we cannot downgrade unity version of asset at the top of document
vrchat-community/creator-docs pull request #97
Opened 2023-12-09 05:34 UTC by anatawa12

2024-01-12 18:55 UTC, Faxmashine requested changes
Thank you for the suggestion! How about rephrasing it slightly?

Note that the "Troubleshooting" section at the bottom of this page already informs the user about being unable to reupload with 2019. But showing that information sooner is still beneficial! 👍

2024-01-12 18:55 UTC, Faxmashine commented on Docs/docs/sdk/upgrade/unity-2022.md
> +:::
```suggestion
:::danger Test your content before uploading it

After successfully uploading a world or avatar with Unity 2022, you won't be able to upload it again with Unity 2019.

:::
```

2024-01-13 06:34 UTC, anatawa12 commented
> Note that the "Troubleshooting" section at the bottom of this page already informs the user about being unable to reupload with 2019. 

I already know that but i think it's not enough so I made this pull request.

I think your suggestion is completely good so I merged suggestions!

2024-01-23 17:56 UTC, Faxmashine approved these changes

2024-01-23 17:56 UTC, merged